/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen;


import com.ke.bella.openapi.jooqgen.tables.Apikey;
import com.ke.bella.openapi.jooqgen.tables.ApikeyChangeLog;
import com.ke.bella.openapi.jooqgen.tables.ApikeyMonthCost;
import com.ke.bella.openapi.jooqgen.tables.ApikeyTransferLog;
import com.ke.bella.openapi.jooqgen.tables.Category;
import com.ke.bella.openapi.jooqgen.tables.Channel;
import com.ke.bella.openapi.jooqgen.tables.Endpoint;
import com.ke.bella.openapi.jooqgen.tables.EndpointCategoryRel;
import com.ke.bella.openapi.jooqgen.tables.Model;
import com.ke.bella.openapi.jooqgen.tables.ModelAuthorizerRel;
import com.ke.bella.openapi.jooqgen.tables.ModelEndpointRel;
import com.ke.bella.openapi.jooqgen.tables.SpaceMember;
import com.ke.bella.openapi.jooqgen.tables.VideoJob;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APIKEY_CHANGE_LOG_IDX_ACTION_TYPE = Internal.createIndex(DSL.name("idx_action_type"), ApikeyChangeLog.APIKEY_CHANGE_LOG, new OrderField[] { ApikeyChangeLog.APIKEY_CHANGE_LOG.ACTION_TYPE }, false);
    public static final Index APIKEY_CHANGE_LOG_IDX_AK_CODE = Internal.createIndex(DSL.name("idx_ak_code"), ApikeyChangeLog.APIKEY_CHANGE_LOG, new OrderField[] { ApikeyChangeLog.APIKEY_CHANGE_LOG.AK_CODE }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_AK_CODE = Internal.createIndex(DSL.name("idx_ak_code"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.AK_CODE }, false);
    public static final Index VIDEO_JOB_IDX_AK_CODE = Internal.createIndex(DSL.name("idx_ak_code"), VideoJob.VIDEO_JOB, new OrderField[] { VideoJob.VIDEO_JOB.AK_CODE }, false);
    public static final Index MODEL_AUTHORIZER_REL_IDX_AUTHORIZER_CODE = Internal.createIndex(DSL.name("idx_authorizer_code"), ModelAuthorizerRel.MODEL_AUTHORIZER_REL, new OrderField[] { ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_CODE }, false);
    public static final Index ENDPOINT_CATEGORY_REL_IDX_CATEGORY_CODE = Internal.createIndex(DSL.name("idx_category_code"), EndpointCategoryRel.ENDPOINT_CATEGORY_REL, new OrderField[] { EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CATEGORY_CODE }, false);
    public static final Index CATEGORY_IDX_CATEGORY_NAME = Internal.createIndex(DSL.name("idx_category_name"), Category.CATEGORY, new OrderField[] { Category.CATEGORY.CATEGORY_NAME }, false);
    public static final Index VIDEO_JOB_IDX_CHANNEL_VIDEO_ID = Internal.createIndex(DSL.name("idx_channel_video_id"), VideoJob.VIDEO_JOB, new OrderField[] { VideoJob.VIDEO_JOB.CHANNEL_CODE, VideoJob.VIDEO_JOB.CHANNEL_VIDEO_ID }, false);
    public static final Index APIKEY_CHANGE_LOG_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), ApikeyChangeLog.APIKEY_CHANGE_LOG, new OrderField[] { ApikeyChangeLog.APIKEY_CHANGE_LOG.CTIME }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.CTIME }, false);
    public static final Index CHANNEL_IDX_ENTITY_TYPE_CODE = Internal.createIndex(DSL.name("idx_entity_type_code"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.ENTITY_TYPE, Channel.CHANNEL.ENTITY_CODE }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_FROM_OWNER = Internal.createIndex(DSL.name("idx_from_owner"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_TYPE, ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_CODE }, false);
    public static final Index APIKEY_IDX_MANAGER_CODE = Internal.createIndex(DSL.name("idx_manager_code"), Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.MANAGER_CODE }, false);
    public static final Index SPACE_MEMBER_IDX_MEMBER_UID = Internal.createIndex(DSL.name("idx_member_uid"), SpaceMember.SPACE_MEMBER, new OrderField[] { SpaceMember.SPACE_MEMBER.MEMBER_UID }, false);
    public static final Index VIDEO_JOB_IDX_MODEL = Internal.createIndex(DSL.name("idx_model"), VideoJob.VIDEO_JOB, new OrderField[] { VideoJob.VIDEO_JOB.MODEL }, false);
    public static final Index MODEL_ENDPOINT_REL_IDX_MODEL_NAME = Internal.createIndex(DSL.name("idx_model_name"), ModelEndpointRel.MODEL_ENDPOINT_REL, new OrderField[] { ModelEndpointRel.MODEL_ENDPOINT_REL.MODEL_NAME }, false);
    public static final Index APIKEY_MONTH_COST_IDX_MONTH = Internal.createIndex(DSL.name("idx_month"), ApikeyMonthCost.APIKEY_MONTH_COST, new OrderField[] { ApikeyMonthCost.APIKEY_MONTH_COST.MONTH }, false);
    public static final Index MODEL_IDX_OWNER_NAME = Internal.createIndex(DSL.name("idx_owner_name"), Model.MODEL, new OrderField[] { Model.MODEL.OWNER_NAME }, false);
    public static final Index APIKEY_IDX_OWNER_TYPE_CODE = Internal.createIndex(DSL.name("idx_owner_type_code"), Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.OWNER_TYPE, Apikey.APIKEY.OWNER_CODE }, false);
    public static final Index MODEL_IDX_OWNER_TYPE_CODE = Internal.createIndex(DSL.name("idx_owner_type_code"), Model.MODEL, new OrderField[] { Model.MODEL.OWNER_TYPE, Model.MODEL.OWNER_CODE }, false);
    public static final Index APIKEY_IDX_PARENT_OUT_ENTITY_CODE = Internal.createIndex(DSL.name("idx_parent_out_entity_code"), Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.PARENT_CODE, Apikey.APIKEY.OUT_ENTITY_CODE }, false);
    public static final Index CHANNEL_IDX_PROTOCOL = Internal.createIndex(DSL.name("idx_protocol"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.PROTOCOL }, false);
    public static final Index CHANNEL_IDX_QUEUE_NAME = Internal.createIndex(DSL.name("idx_queue_name"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.QUEUE_NAME }, false);
    public static final Index ENDPOINT_CATEGORY_REL_IDX_SORT = Internal.createIndex(DSL.name("idx_sort"), EndpointCategoryRel.ENDPOINT_CATEGORY_REL, new OrderField[] { EndpointCategoryRel.ENDPOINT_CATEGORY_REL.SORT }, false);
    public static final Index VIDEO_JOB_IDX_SPACE_CODE = Internal.createIndex(DSL.name("idx_space_code"), VideoJob.VIDEO_JOB, new OrderField[] { VideoJob.VIDEO_JOB.SPACE_CODE }, false);
    public static final Index VIDEO_JOB_IDX_STATUS = Internal.createIndex(DSL.name("idx_status"), VideoJob.VIDEO_JOB, new OrderField[] { VideoJob.VIDEO_JOB.STATUS }, false);
    public static final Index CHANNEL_IDX_SUPPLIER = Internal.createIndex(DSL.name("idx_supplier"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.SUPPLIER }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_TO_OWNER = Internal.createIndex(DSL.name("idx_to_owner"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_TYPE, ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_CODE }, false);
    public static final Index ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_NAME = Internal.createIndex(DSL.name("uniq_idx_uni_endpoint_name"), Endpoint.ENDPOINT, new OrderField[] { Endpoint.ENDPOINT.ENDPOINT_NAME }, false);
}
