/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables;


import com.ke.bella.openapi.jooqgen.DefaultSchema;
import com.ke.bella.openapi.jooqgen.Indexes;
import com.ke.bella.openapi.jooqgen.Keys;
import com.ke.bella.openapi.jooqgen.tables.records.VideoJobRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 视频任务表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VideoJob extends TableImpl<VideoJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>video_job</code>
     */
    public static final VideoJob VIDEO_JOB = new VideoJob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VideoJobRecord> getRecordType() {
        return VideoJobRecord.class;
    }

    /**
     * The column <code>video_job.id</code>. 主键ID
     */
    public final TableField<VideoJobRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>video_job.video_id</code>. 视频ID/任务ID
     */
    public final TableField<VideoJobRecord, String> VIDEO_ID = createField(DSL.name("video_id"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "视频ID/任务ID");

    /**
     * The column <code>video_job.space_code</code>. 空间编码
     */
    public final TableField<VideoJobRecord, String> SPACE_CODE = createField(DSL.name("space_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "空间编码");

    /**
     * The column <code>video_job.ak_code</code>. API Key编码
     */
    public final TableField<VideoJobRecord, String> AK_CODE = createField(DSL.name("ak_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "API Key编码");

    /**
     * The column <code>video_job.model</code>. 模型名称
     */
    public final TableField<VideoJobRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "模型名称");

    /**
     * The column <code>video_job.progress</code>. 进度百分比
     */
    public final TableField<VideoJobRecord, Integer> PROGRESS = createField(DSL.name("progress"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "进度百分比");

    /**
     * The column <code>video_job.prompt</code>. 提示词
     */
    public final TableField<VideoJobRecord, String> PROMPT = createField(DSL.name("prompt"), SQLDataType.CLOB, this, "提示词");

    /**
     * The column <code>video_job.input_reference_file_id</code>.
     * 输入参考文件ID（用户上传的参考视频/图片）
     */
    public final TableField<VideoJobRecord, String> INPUT_REFERENCE_FILE_ID = createField(DSL.name("input_reference_file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "输入参考文件ID（用户上传的参考视频/图片）");

    /**
     * The column <code>video_job.seconds</code>. 时长
     */
    public final TableField<VideoJobRecord, Long> SECONDS = createField(DSL.name("seconds"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "时长");

    /**
     * The column <code>video_job.size</code>. 视频尺寸
     */
    public final TableField<VideoJobRecord, String> SIZE = createField(DSL.name("size"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "视频尺寸");

    /**
     * The column <code>video_job.remixed_from_video_id</code>. 源视频ID（remix任务）
     */
    public final TableField<VideoJobRecord, String> REMIXED_FROM_VIDEO_ID = createField(DSL.name("remixed_from_video_id"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "源视频ID（remix任务）");

    /**
     * The column <code>video_job.completed_at</code>. 视频任务完成时间
     */
    public final TableField<VideoJobRecord, LocalDateTime> COMPLETED_AT = createField(DSL.name("completed_at"), SQLDataType.LOCALDATETIME(0), this, "视频任务完成时间");

    /**
     * The column <code>video_job.expires_at</code>. 视频任务下载过期时间
     */
    public final TableField<VideoJobRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(0), this, "视频任务下载过期时间");

    /**
     * The column <code>video_job.status</code>.
     * 任务状态(queued/submitting/processing/completed/failed/cancelled)
     */
    public final TableField<VideoJobRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("queued", SQLDataType.VARCHAR)), this, "任务状态(queued/submitting/processing/completed/failed/cancelled)");

    /**
     * The column <code>video_job.bound_file_id</code>. 绑定的文件ID（用于file api转储检索）
     */
    public final TableField<VideoJobRecord, String> BOUND_FILE_ID = createField(DSL.name("bound_file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "绑定的文件ID（用于file api转储检索）");

    /**
     * The column <code>video_job.callback_url</code>. 回调URL
     */
    public final TableField<VideoJobRecord, String> CALLBACK_URL = createField(DSL.name("callback_url"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "回调URL");

    /**
     * The column <code>video_job.callback_status</code>.
     * 回调状态(-1：回调失败；0：未回调；1：回调成功)
     */
    public final TableField<VideoJobRecord, Byte> CALLBACK_STATUS = createField(DSL.name("callback_status"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "回调状态(-1：回调失败；0：未回调；1：回调成功)");

    /**
     * The column <code>video_job.channel_code</code>. 渠道编码
     */
    public final TableField<VideoJobRecord, String> CHANNEL_CODE = createField(DSL.name("channel_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "渠道编码");

    /**
     * The column <code>video_job.channel_video_id</code>. 渠道视频ID
     */
    public final TableField<VideoJobRecord, String> CHANNEL_VIDEO_ID = createField(DSL.name("channel_video_id"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "渠道视频ID");

    /**
     * The column <code>video_job.error</code>. 错误详情（JSON格式，包含code/message等）
     */
    public final TableField<VideoJobRecord, String> ERROR = createField(DSL.name("error"), SQLDataType.CLOB, this, "错误详情（JSON格式，包含code/message等）");

    /**
     * The column <code>video_job.cuid</code>. 创建人ID
     */
    public final TableField<VideoJobRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "创建人ID");

    /**
     * The column <code>video_job.cu_name</code>. 创建人姓名
     */
    public final TableField<VideoJobRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>video_job.muid</code>. 修改人ID
     */
    public final TableField<VideoJobRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "修改人ID");

    /**
     * The column <code>video_job.mu_name</code>. 修改人姓名
     */
    public final TableField<VideoJobRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "修改人姓名");

    /**
     * The column <code>video_job.ctime</code>.
     */
    public final TableField<VideoJobRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>video_job.mtime</code>.
     */
    public final TableField<VideoJobRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private VideoJob(Name alias, Table<VideoJobRecord> aliased) {
        this(alias, aliased, null);
    }

    private VideoJob(Name alias, Table<VideoJobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("视频任务表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>video_job</code> table reference
     */
    public VideoJob(String alias) {
        this(DSL.name(alias), VIDEO_JOB);
    }

    /**
     * Create an aliased <code>video_job</code> table reference
     */
    public VideoJob(Name alias) {
        this(alias, VIDEO_JOB);
    }

    /**
     * Create a <code>video_job</code> table reference
     */
    public VideoJob() {
        this(DSL.name("video_job"), null);
    }

    public <O extends Record> VideoJob(Table<O> child, ForeignKey<O, VideoJobRecord> key) {
        super(child, key, VIDEO_JOB);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VIDEO_JOB_IDX_AK_CODE, Indexes.VIDEO_JOB_IDX_CHANNEL_VIDEO_ID, Indexes.VIDEO_JOB_IDX_MODEL, Indexes.VIDEO_JOB_IDX_SPACE_CODE, Indexes.VIDEO_JOB_IDX_STATUS);
    }

    @Override
    public Identity<VideoJobRecord, Long> getIdentity() {
        return (Identity<VideoJobRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VideoJobRecord> getPrimaryKey() {
        return Keys.KEY_VIDEO_JOB_PRIMARY;
    }

    @Override
    public List<UniqueKey<VideoJobRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_VIDEO_JOB_UNIQ_IDX_JOB_ID);
    }

    @Override
    public VideoJob as(String alias) {
        return new VideoJob(DSL.name(alias), this);
    }

    @Override
    public VideoJob as(Name alias) {
        return new VideoJob(alias, this);
    }

    @Override
    public VideoJob as(Table<?> alias) {
        return new VideoJob(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VideoJob rename(String name) {
        return new VideoJob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VideoJob rename(Name name) {
        return new VideoJob(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VideoJob rename(Table<?> name) {
        return new VideoJob(name.getQualifiedName(), null);
    }
}
