/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * API Key所有权转移审计日志表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyTransferLogDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String akCode;
    private String fromOwnerType;
    private String fromOwnerCode;
    private String fromOwnerName;
    private String toOwnerType;
    private String toOwnerCode;
    private String toOwnerName;
    private String transferReason;
    private String status;
    private Long operatorUid;
    private String operatorName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public ApikeyTransferLogDB() {}

    public ApikeyTransferLogDB(ApikeyTransferLogDB value) {
        this.id = value.id;
        this.akCode = value.akCode;
        this.fromOwnerType = value.fromOwnerType;
        this.fromOwnerCode = value.fromOwnerCode;
        this.fromOwnerName = value.fromOwnerName;
        this.toOwnerType = value.toOwnerType;
        this.toOwnerCode = value.toOwnerCode;
        this.toOwnerName = value.toOwnerName;
        this.transferReason = value.transferReason;
        this.status = value.status;
        this.operatorUid = value.operatorUid;
        this.operatorName = value.operatorName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ApikeyTransferLogDB(
        Long id,
        String akCode,
        String fromOwnerType,
        String fromOwnerCode,
        String fromOwnerName,
        String toOwnerType,
        String toOwnerCode,
        String toOwnerName,
        String transferReason,
        String status,
        Long operatorUid,
        String operatorName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.akCode = akCode;
        this.fromOwnerType = fromOwnerType;
        this.fromOwnerCode = fromOwnerCode;
        this.fromOwnerName = fromOwnerName;
        this.toOwnerType = toOwnerType;
        this.toOwnerCode = toOwnerCode;
        this.toOwnerName = toOwnerName;
        this.transferReason = transferReason;
        this.status = status;
        this.operatorUid = operatorUid;
        this.operatorName = operatorName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>apikey_transfer_log.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>apikey_transfer_log.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>apikey_transfer_log.ak_code</code>. API Key编码
     */
    public String getAkCode() {
        return this.akCode;
    }

    /**
     * Setter for <code>apikey_transfer_log.ak_code</code>. API Key编码
     */
    public void setAkCode(String akCode) {
        this.akCode = akCode;
    }

    /**
     * Getter for <code>apikey_transfer_log.from_owner_type</code>. 原所有者类型
     */
    public String getFromOwnerType() {
        return this.fromOwnerType;
    }

    /**
     * Setter for <code>apikey_transfer_log.from_owner_type</code>. 原所有者类型
     */
    public void setFromOwnerType(String fromOwnerType) {
        this.fromOwnerType = fromOwnerType;
    }

    /**
     * Getter for <code>apikey_transfer_log.from_owner_code</code>. 原所有者编码
     */
    public String getFromOwnerCode() {
        return this.fromOwnerCode;
    }

    /**
     * Setter for <code>apikey_transfer_log.from_owner_code</code>. 原所有者编码
     */
    public void setFromOwnerCode(String fromOwnerCode) {
        this.fromOwnerCode = fromOwnerCode;
    }

    /**
     * Getter for <code>apikey_transfer_log.from_owner_name</code>. 原所有者姓名
     */
    public String getFromOwnerName() {
        return this.fromOwnerName;
    }

    /**
     * Setter for <code>apikey_transfer_log.from_owner_name</code>. 原所有者姓名
     */
    public void setFromOwnerName(String fromOwnerName) {
        this.fromOwnerName = fromOwnerName;
    }

    /**
     * Getter for <code>apikey_transfer_log.to_owner_type</code>. 新所有者类型
     */
    public String getToOwnerType() {
        return this.toOwnerType;
    }

    /**
     * Setter for <code>apikey_transfer_log.to_owner_type</code>. 新所有者类型
     */
    public void setToOwnerType(String toOwnerType) {
        this.toOwnerType = toOwnerType;
    }

    /**
     * Getter for <code>apikey_transfer_log.to_owner_code</code>. 新所有者编码
     */
    public String getToOwnerCode() {
        return this.toOwnerCode;
    }

    /**
     * Setter for <code>apikey_transfer_log.to_owner_code</code>. 新所有者编码
     */
    public void setToOwnerCode(String toOwnerCode) {
        this.toOwnerCode = toOwnerCode;
    }

    /**
     * Getter for <code>apikey_transfer_log.to_owner_name</code>. 新所有者姓名
     */
    public String getToOwnerName() {
        return this.toOwnerName;
    }

    /**
     * Setter for <code>apikey_transfer_log.to_owner_name</code>. 新所有者姓名
     */
    public void setToOwnerName(String toOwnerName) {
        this.toOwnerName = toOwnerName;
    }

    /**
     * Getter for <code>apikey_transfer_log.transfer_reason</code>. 转移原因
     */
    public String getTransferReason() {
        return this.transferReason;
    }

    /**
     * Setter for <code>apikey_transfer_log.transfer_reason</code>. 转移原因
     */
    public void setTransferReason(String transferReason) {
        this.transferReason = transferReason;
    }

    /**
     * Getter for <code>apikey_transfer_log.status</code>.
     * 转移状态(pending/completed/failed)
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>apikey_transfer_log.status</code>.
     * 转移状态(pending/completed/failed)
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>apikey_transfer_log.operator_uid</code>. 操作人用户ID
     */
    public Long getOperatorUid() {
        return this.operatorUid;
    }

    /**
     * Setter for <code>apikey_transfer_log.operator_uid</code>. 操作人用户ID
     */
    public void setOperatorUid(Long operatorUid) {
        this.operatorUid = operatorUid;
    }

    /**
     * Getter for <code>apikey_transfer_log.operator_name</code>. 操作人姓名
     */
    public String getOperatorName() {
        return this.operatorName;
    }

    /**
     * Setter for <code>apikey_transfer_log.operator_name</code>. 操作人姓名
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * Getter for <code>apikey_transfer_log.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>apikey_transfer_log.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>apikey_transfer_log.mtime</code>. 更新时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>apikey_transfer_log.mtime</code>. 更新时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ApikeyTransferLogDB other = (ApikeyTransferLogDB) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.akCode == null) {
            if (other.akCode != null)
                return false;
        }
        else if (!this.akCode.equals(other.akCode))
            return false;
        if (this.fromOwnerType == null) {
            if (other.fromOwnerType != null)
                return false;
        }
        else if (!this.fromOwnerType.equals(other.fromOwnerType))
            return false;
        if (this.fromOwnerCode == null) {
            if (other.fromOwnerCode != null)
                return false;
        }
        else if (!this.fromOwnerCode.equals(other.fromOwnerCode))
            return false;
        if (this.fromOwnerName == null) {
            if (other.fromOwnerName != null)
                return false;
        }
        else if (!this.fromOwnerName.equals(other.fromOwnerName))
            return false;
        if (this.toOwnerType == null) {
            if (other.toOwnerType != null)
                return false;
        }
        else if (!this.toOwnerType.equals(other.toOwnerType))
            return false;
        if (this.toOwnerCode == null) {
            if (other.toOwnerCode != null)
                return false;
        }
        else if (!this.toOwnerCode.equals(other.toOwnerCode))
            return false;
        if (this.toOwnerName == null) {
            if (other.toOwnerName != null)
                return false;
        }
        else if (!this.toOwnerName.equals(other.toOwnerName))
            return false;
        if (this.transferReason == null) {
            if (other.transferReason != null)
                return false;
        }
        else if (!this.transferReason.equals(other.transferReason))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.operatorUid == null) {
            if (other.operatorUid != null)
                return false;
        }
        else if (!this.operatorUid.equals(other.operatorUid))
            return false;
        if (this.operatorName == null) {
            if (other.operatorName != null)
                return false;
        }
        else if (!this.operatorName.equals(other.operatorName))
            return false;
        if (this.ctime == null) {
            if (other.ctime != null)
                return false;
        }
        else if (!this.ctime.equals(other.ctime))
            return false;
        if (this.mtime == null) {
            if (other.mtime != null)
                return false;
        }
        else if (!this.mtime.equals(other.mtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.akCode == null) ? 0 : this.akCode.hashCode());
        result = prime * result + ((this.fromOwnerType == null) ? 0 : this.fromOwnerType.hashCode());
        result = prime * result + ((this.fromOwnerCode == null) ? 0 : this.fromOwnerCode.hashCode());
        result = prime * result + ((this.fromOwnerName == null) ? 0 : this.fromOwnerName.hashCode());
        result = prime * result + ((this.toOwnerType == null) ? 0 : this.toOwnerType.hashCode());
        result = prime * result + ((this.toOwnerCode == null) ? 0 : this.toOwnerCode.hashCode());
        result = prime * result + ((this.toOwnerName == null) ? 0 : this.toOwnerName.hashCode());
        result = prime * result + ((this.transferReason == null) ? 0 : this.transferReason.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.operatorUid == null) ? 0 : this.operatorUid.hashCode());
        result = prime * result + ((this.operatorName == null) ? 0 : this.operatorName.hashCode());
        result = prime * result + ((this.ctime == null) ? 0 : this.ctime.hashCode());
        result = prime * result + ((this.mtime == null) ? 0 : this.mtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApikeyTransferLogDB (");

        sb.append(id);
        sb.append(", ").append(akCode);
        sb.append(", ").append(fromOwnerType);
        sb.append(", ").append(fromOwnerCode);
        sb.append(", ").append(fromOwnerName);
        sb.append(", ").append(toOwnerType);
        sb.append(", ").append(toOwnerCode);
        sb.append(", ").append(toOwnerName);
        sb.append(", ").append(transferReason);
        sb.append(", ").append(status);
        sb.append(", ").append(operatorUid);
        sb.append(", ").append(operatorName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
