/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * API Key变更历史表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyChangeLogDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String actionType;
    private String akCode;
    private String affectedCodes;
    private String fromOwnerType;
    private String fromOwnerCode;
    private String fromOwnerName;
    private String toOwnerType;
    private String toOwnerCode;
    private String toOwnerName;
    private String fromParentCode;
    private String toParentCode;
    private String fromManagerCode;
    private String fromManagerName;
    private String toManagerCode;
    private String toManagerName;
    private String reason;
    private String status;
    private Long operatorUid;
    private String operatorName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public ApikeyChangeLogDB() {}

    public ApikeyChangeLogDB(ApikeyChangeLogDB value) {
        this.id = value.id;
        this.actionType = value.actionType;
        this.akCode = value.akCode;
        this.affectedCodes = value.affectedCodes;
        this.fromOwnerType = value.fromOwnerType;
        this.fromOwnerCode = value.fromOwnerCode;
        this.fromOwnerName = value.fromOwnerName;
        this.toOwnerType = value.toOwnerType;
        this.toOwnerCode = value.toOwnerCode;
        this.toOwnerName = value.toOwnerName;
        this.fromParentCode = value.fromParentCode;
        this.toParentCode = value.toParentCode;
        this.fromManagerCode = value.fromManagerCode;
        this.fromManagerName = value.fromManagerName;
        this.toManagerCode = value.toManagerCode;
        this.toManagerName = value.toManagerName;
        this.reason = value.reason;
        this.status = value.status;
        this.operatorUid = value.operatorUid;
        this.operatorName = value.operatorName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ApikeyChangeLogDB(
        Long id,
        String actionType,
        String akCode,
        String affectedCodes,
        String fromOwnerType,
        String fromOwnerCode,
        String fromOwnerName,
        String toOwnerType,
        String toOwnerCode,
        String toOwnerName,
        String fromParentCode,
        String toParentCode,
        String fromManagerCode,
        String fromManagerName,
        String toManagerCode,
        String toManagerName,
        String reason,
        String status,
        Long operatorUid,
        String operatorName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.actionType = actionType;
        this.akCode = akCode;
        this.affectedCodes = affectedCodes;
        this.fromOwnerType = fromOwnerType;
        this.fromOwnerCode = fromOwnerCode;
        this.fromOwnerName = fromOwnerName;
        this.toOwnerType = toOwnerType;
        this.toOwnerCode = toOwnerCode;
        this.toOwnerName = toOwnerName;
        this.fromParentCode = fromParentCode;
        this.toParentCode = toParentCode;
        this.fromManagerCode = fromManagerCode;
        this.fromManagerName = fromManagerName;
        this.toManagerCode = toManagerCode;
        this.toManagerName = toManagerName;
        this.reason = reason;
        this.status = status;
        this.operatorUid = operatorUid;
        this.operatorName = operatorName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>apikey_change_log.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>apikey_change_log.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>apikey_change_log.action_type</code>.
     * 变更类型(owner_transfer/owner_change/parent_change)
     */
    public String getActionType() {
        return this.actionType;
    }

    /**
     * Setter for <code>apikey_change_log.action_type</code>.
     * 变更类型(owner_transfer/owner_change/parent_change)
     */
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    /**
     * Getter for <code>apikey_change_log.ak_code</code>. 入口AK编码
     */
    public String getAkCode() {
        return this.akCode;
    }

    /**
     * Setter for <code>apikey_change_log.ak_code</code>. 入口AK编码
     */
    public void setAkCode(String akCode) {
        this.akCode = akCode;
    }

    /**
     * Getter for <code>apikey_change_log.affected_codes</code>. 受影响AK编码列表(JSON)
     */
    public String getAffectedCodes() {
        return this.affectedCodes;
    }

    /**
     * Setter for <code>apikey_change_log.affected_codes</code>. 受影响AK编码列表(JSON)
     */
    public void setAffectedCodes(String affectedCodes) {
        this.affectedCodes = affectedCodes;
    }

    /**
     * Getter for <code>apikey_change_log.from_owner_type</code>. 变更前所有者类型
     */
    public String getFromOwnerType() {
        return this.fromOwnerType;
    }

    /**
     * Setter for <code>apikey_change_log.from_owner_type</code>. 变更前所有者类型
     */
    public void setFromOwnerType(String fromOwnerType) {
        this.fromOwnerType = fromOwnerType;
    }

    /**
     * Getter for <code>apikey_change_log.from_owner_code</code>. 变更前所有者编码
     */
    public String getFromOwnerCode() {
        return this.fromOwnerCode;
    }

    /**
     * Setter for <code>apikey_change_log.from_owner_code</code>. 变更前所有者编码
     */
    public void setFromOwnerCode(String fromOwnerCode) {
        this.fromOwnerCode = fromOwnerCode;
    }

    /**
     * Getter for <code>apikey_change_log.from_owner_name</code>. 变更前所有者名称
     */
    public String getFromOwnerName() {
        return this.fromOwnerName;
    }

    /**
     * Setter for <code>apikey_change_log.from_owner_name</code>. 变更前所有者名称
     */
    public void setFromOwnerName(String fromOwnerName) {
        this.fromOwnerName = fromOwnerName;
    }

    /**
     * Getter for <code>apikey_change_log.to_owner_type</code>. 变更后所有者类型
     */
    public String getToOwnerType() {
        return this.toOwnerType;
    }

    /**
     * Setter for <code>apikey_change_log.to_owner_type</code>. 变更后所有者类型
     */
    public void setToOwnerType(String toOwnerType) {
        this.toOwnerType = toOwnerType;
    }

    /**
     * Getter for <code>apikey_change_log.to_owner_code</code>. 变更后所有者编码
     */
    public String getToOwnerCode() {
        return this.toOwnerCode;
    }

    /**
     * Setter for <code>apikey_change_log.to_owner_code</code>. 变更后所有者编码
     */
    public void setToOwnerCode(String toOwnerCode) {
        this.toOwnerCode = toOwnerCode;
    }

    /**
     * Getter for <code>apikey_change_log.to_owner_name</code>. 变更后所有者名称
     */
    public String getToOwnerName() {
        return this.toOwnerName;
    }

    /**
     * Setter for <code>apikey_change_log.to_owner_name</code>. 变更后所有者名称
     */
    public void setToOwnerName(String toOwnerName) {
        this.toOwnerName = toOwnerName;
    }

    /**
     * Getter for <code>apikey_change_log.from_parent_code</code>. 变更前父AK编码
     */
    public String getFromParentCode() {
        return this.fromParentCode;
    }

    /**
     * Setter for <code>apikey_change_log.from_parent_code</code>. 变更前父AK编码
     */
    public void setFromParentCode(String fromParentCode) {
        this.fromParentCode = fromParentCode;
    }

    /**
     * Getter for <code>apikey_change_log.to_parent_code</code>. 变更后父AK编码
     */
    public String getToParentCode() {
        return this.toParentCode;
    }

    /**
     * Setter for <code>apikey_change_log.to_parent_code</code>. 变更后父AK编码
     */
    public void setToParentCode(String toParentCode) {
        this.toParentCode = toParentCode;
    }

    /**
     * Getter for <code>apikey_change_log.from_manager_code</code>. 变更前管理者编码
     */
    public String getFromManagerCode() {
        return this.fromManagerCode;
    }

    /**
     * Setter for <code>apikey_change_log.from_manager_code</code>. 变更前管理者编码
     */
    public void setFromManagerCode(String fromManagerCode) {
        this.fromManagerCode = fromManagerCode;
    }

    /**
     * Getter for <code>apikey_change_log.from_manager_name</code>. 变更前管理者名称
     */
    public String getFromManagerName() {
        return this.fromManagerName;
    }

    /**
     * Setter for <code>apikey_change_log.from_manager_name</code>. 变更前管理者名称
     */
    public void setFromManagerName(String fromManagerName) {
        this.fromManagerName = fromManagerName;
    }

    /**
     * Getter for <code>apikey_change_log.to_manager_code</code>. 变更后管理者编码
     */
    public String getToManagerCode() {
        return this.toManagerCode;
    }

    /**
     * Setter for <code>apikey_change_log.to_manager_code</code>. 变更后管理者编码
     */
    public void setToManagerCode(String toManagerCode) {
        this.toManagerCode = toManagerCode;
    }

    /**
     * Getter for <code>apikey_change_log.to_manager_name</code>. 变更后管理者名称
     */
    public String getToManagerName() {
        return this.toManagerName;
    }

    /**
     * Setter for <code>apikey_change_log.to_manager_name</code>. 变更后管理者名称
     */
    public void setToManagerName(String toManagerName) {
        this.toManagerName = toManagerName;
    }

    /**
     * Getter for <code>apikey_change_log.reason</code>. 变更原因
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Setter for <code>apikey_change_log.reason</code>. 变更原因
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Getter for <code>apikey_change_log.status</code>. 变更状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>apikey_change_log.status</code>. 变更状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>apikey_change_log.operator_uid</code>. 操作人用户ID
     */
    public Long getOperatorUid() {
        return this.operatorUid;
    }

    /**
     * Setter for <code>apikey_change_log.operator_uid</code>. 操作人用户ID
     */
    public void setOperatorUid(Long operatorUid) {
        this.operatorUid = operatorUid;
    }

    /**
     * Getter for <code>apikey_change_log.operator_name</code>. 操作人姓名
     */
    public String getOperatorName() {
        return this.operatorName;
    }

    /**
     * Setter for <code>apikey_change_log.operator_name</code>. 操作人姓名
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * Getter for <code>apikey_change_log.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>apikey_change_log.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>apikey_change_log.mtime</code>. 更新时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>apikey_change_log.mtime</code>. 更新时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ApikeyChangeLogDB other = (ApikeyChangeLogDB) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.actionType == null) {
            if (other.actionType != null)
                return false;
        }
        else if (!this.actionType.equals(other.actionType))
            return false;
        if (this.akCode == null) {
            if (other.akCode != null)
                return false;
        }
        else if (!this.akCode.equals(other.akCode))
            return false;
        if (this.affectedCodes == null) {
            if (other.affectedCodes != null)
                return false;
        }
        else if (!this.affectedCodes.equals(other.affectedCodes))
            return false;
        if (this.fromOwnerType == null) {
            if (other.fromOwnerType != null)
                return false;
        }
        else if (!this.fromOwnerType.equals(other.fromOwnerType))
            return false;
        if (this.fromOwnerCode == null) {
            if (other.fromOwnerCode != null)
                return false;
        }
        else if (!this.fromOwnerCode.equals(other.fromOwnerCode))
            return false;
        if (this.fromOwnerName == null) {
            if (other.fromOwnerName != null)
                return false;
        }
        else if (!this.fromOwnerName.equals(other.fromOwnerName))
            return false;
        if (this.toOwnerType == null) {
            if (other.toOwnerType != null)
                return false;
        }
        else if (!this.toOwnerType.equals(other.toOwnerType))
            return false;
        if (this.toOwnerCode == null) {
            if (other.toOwnerCode != null)
                return false;
        }
        else if (!this.toOwnerCode.equals(other.toOwnerCode))
            return false;
        if (this.toOwnerName == null) {
            if (other.toOwnerName != null)
                return false;
        }
        else if (!this.toOwnerName.equals(other.toOwnerName))
            return false;
        if (this.fromParentCode == null) {
            if (other.fromParentCode != null)
                return false;
        }
        else if (!this.fromParentCode.equals(other.fromParentCode))
            return false;
        if (this.toParentCode == null) {
            if (other.toParentCode != null)
                return false;
        }
        else if (!this.toParentCode.equals(other.toParentCode))
            return false;
        if (this.fromManagerCode == null) {
            if (other.fromManagerCode != null)
                return false;
        }
        else if (!this.fromManagerCode.equals(other.fromManagerCode))
            return false;
        if (this.fromManagerName == null) {
            if (other.fromManagerName != null)
                return false;
        }
        else if (!this.fromManagerName.equals(other.fromManagerName))
            return false;
        if (this.toManagerCode == null) {
            if (other.toManagerCode != null)
                return false;
        }
        else if (!this.toManagerCode.equals(other.toManagerCode))
            return false;
        if (this.toManagerName == null) {
            if (other.toManagerName != null)
                return false;
        }
        else if (!this.toManagerName.equals(other.toManagerName))
            return false;
        if (this.reason == null) {
            if (other.reason != null)
                return false;
        }
        else if (!this.reason.equals(other.reason))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.operatorUid == null) {
            if (other.operatorUid != null)
                return false;
        }
        else if (!this.operatorUid.equals(other.operatorUid))
            return false;
        if (this.operatorName == null) {
            if (other.operatorName != null)
                return false;
        }
        else if (!this.operatorName.equals(other.operatorName))
            return false;
        if (this.ctime == null) {
            if (other.ctime != null)
                return false;
        }
        else if (!this.ctime.equals(other.ctime))
            return false;
        if (this.mtime == null) {
            if (other.mtime != null)
                return false;
        }
        else if (!this.mtime.equals(other.mtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.actionType == null) ? 0 : this.actionType.hashCode());
        result = prime * result + ((this.akCode == null) ? 0 : this.akCode.hashCode());
        result = prime * result + ((this.affectedCodes == null) ? 0 : this.affectedCodes.hashCode());
        result = prime * result + ((this.fromOwnerType == null) ? 0 : this.fromOwnerType.hashCode());
        result = prime * result + ((this.fromOwnerCode == null) ? 0 : this.fromOwnerCode.hashCode());
        result = prime * result + ((this.fromOwnerName == null) ? 0 : this.fromOwnerName.hashCode());
        result = prime * result + ((this.toOwnerType == null) ? 0 : this.toOwnerType.hashCode());
        result = prime * result + ((this.toOwnerCode == null) ? 0 : this.toOwnerCode.hashCode());
        result = prime * result + ((this.toOwnerName == null) ? 0 : this.toOwnerName.hashCode());
        result = prime * result + ((this.fromParentCode == null) ? 0 : this.fromParentCode.hashCode());
        result = prime * result + ((this.toParentCode == null) ? 0 : this.toParentCode.hashCode());
        result = prime * result + ((this.fromManagerCode == null) ? 0 : this.fromManagerCode.hashCode());
        result = prime * result + ((this.fromManagerName == null) ? 0 : this.fromManagerName.hashCode());
        result = prime * result + ((this.toManagerCode == null) ? 0 : this.toManagerCode.hashCode());
        result = prime * result + ((this.toManagerName == null) ? 0 : this.toManagerName.hashCode());
        result = prime * result + ((this.reason == null) ? 0 : this.reason.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.operatorUid == null) ? 0 : this.operatorUid.hashCode());
        result = prime * result + ((this.operatorName == null) ? 0 : this.operatorName.hashCode());
        result = prime * result + ((this.ctime == null) ? 0 : this.ctime.hashCode());
        result = prime * result + ((this.mtime == null) ? 0 : this.mtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApikeyChangeLogDB (");

        sb.append(id);
        sb.append(", ").append(actionType);
        sb.append(", ").append(akCode);
        sb.append(", ").append(affectedCodes);
        sb.append(", ").append(fromOwnerType);
        sb.append(", ").append(fromOwnerCode);
        sb.append(", ").append(fromOwnerName);
        sb.append(", ").append(toOwnerType);
        sb.append(", ").append(toOwnerCode);
        sb.append(", ").append(toOwnerName);
        sb.append(", ").append(fromParentCode);
        sb.append(", ").append(toParentCode);
        sb.append(", ").append(fromManagerCode);
        sb.append(", ").append(fromManagerName);
        sb.append(", ").append(toManagerCode);
        sb.append(", ").append(toManagerName);
        sb.append(", ").append(reason);
        sb.append(", ").append(status);
        sb.append(", ").append(operatorUid);
        sb.append(", ").append(operatorName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
