/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 类目
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String categoryCode;
    private String categoryName;
    private String parentCode;
    private String status;
    private Long cuid;
    private String cuName;
    private Long muid;
    private String muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public CategoryDB() {}

    public CategoryDB(CategoryDB value) {
        this.id = value.id;
        this.categoryCode = value.categoryCode;
        this.categoryName = value.categoryName;
        this.parentCode = value.parentCode;
        this.status = value.status;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public CategoryDB(
        Long id,
        String categoryCode,
        String categoryName,
        String parentCode,
        String status,
        Long cuid,
        String cuName,
        Long muid,
        String muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.categoryCode = categoryCode;
        this.categoryName = categoryName;
        this.parentCode = parentCode;
        this.status = status;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>category.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>category.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>category.category_code</code>. 类目编码
     */
    public String getCategoryCode() {
        return this.categoryCode;
    }

    /**
     * Setter for <code>category.category_code</code>. 类目编码
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * Getter for <code>category.category_name</code>. 类目名
     */
    public String getCategoryName() {
        return this.categoryName;
    }

    /**
     * Setter for <code>category.category_name</code>. 类目名
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * Getter for <code>category.parent_code</code>. 父类目编码
     */
    public String getParentCode() {
        return this.parentCode;
    }

    /**
     * Setter for <code>category.parent_code</code>. 父类目编码
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * Getter for <code>category.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>category.status</code>. 状态(active/inactive)
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>category.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>category.cuid</code>. 创建人id
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>category.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>category.cu_name</code>. 创建人姓名
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>category.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>category.muid</code>. 编辑人id
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>category.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>category.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>category.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>category.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>category.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>category.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CategoryDB other = (CategoryDB) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.categoryCode == null) {
            if (other.categoryCode != null)
                return false;
        }
        else if (!this.categoryCode.equals(other.categoryCode))
            return false;
        if (this.categoryName == null) {
            if (other.categoryName != null)
                return false;
        }
        else if (!this.categoryName.equals(other.categoryName))
            return false;
        if (this.parentCode == null) {
            if (other.parentCode != null)
                return false;
        }
        else if (!this.parentCode.equals(other.parentCode))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.cuid == null) {
            if (other.cuid != null)
                return false;
        }
        else if (!this.cuid.equals(other.cuid))
            return false;
        if (this.cuName == null) {
            if (other.cuName != null)
                return false;
        }
        else if (!this.cuName.equals(other.cuName))
            return false;
        if (this.muid == null) {
            if (other.muid != null)
                return false;
        }
        else if (!this.muid.equals(other.muid))
            return false;
        if (this.muName == null) {
            if (other.muName != null)
                return false;
        }
        else if (!this.muName.equals(other.muName))
            return false;
        if (this.ctime == null) {
            if (other.ctime != null)
                return false;
        }
        else if (!this.ctime.equals(other.ctime))
            return false;
        if (this.mtime == null) {
            if (other.mtime != null)
                return false;
        }
        else if (!this.mtime.equals(other.mtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.categoryCode == null) ? 0 : this.categoryCode.hashCode());
        result = prime * result + ((this.categoryName == null) ? 0 : this.categoryName.hashCode());
        result = prime * result + ((this.parentCode == null) ? 0 : this.parentCode.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.cuid == null) ? 0 : this.cuid.hashCode());
        result = prime * result + ((this.cuName == null) ? 0 : this.cuName.hashCode());
        result = prime * result + ((this.muid == null) ? 0 : this.muid.hashCode());
        result = prime * result + ((this.muName == null) ? 0 : this.muName.hashCode());
        result = prime * result + ((this.ctime == null) ? 0 : this.ctime.hashCode());
        result = prime * result + ((this.mtime == null) ? 0 : this.mtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategoryDB (");

        sb.append(id);
        sb.append(", ").append(categoryCode);
        sb.append(", ").append(categoryName);
        sb.append(", ").append(parentCode);
        sb.append(", ").append(status);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
