/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 模型授权信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelAuthorizerRelDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String modelName;
    private String authorizerType;
    private String authorizerCode;
    private String authorizerName;
    private Long cuid;
    private String cuName;
    private Long muid;
    private String muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public ModelAuthorizerRelDB() {}

    public ModelAuthorizerRelDB(ModelAuthorizerRelDB value) {
        this.id = value.id;
        this.modelName = value.modelName;
        this.authorizerType = value.authorizerType;
        this.authorizerCode = value.authorizerCode;
        this.authorizerName = value.authorizerName;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ModelAuthorizerRelDB(
        Long id,
        String modelName,
        String authorizerType,
        String authorizerCode,
        String authorizerName,
        Long cuid,
        String cuName,
        Long muid,
        String muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.modelName = modelName;
        this.authorizerType = authorizerType;
        this.authorizerCode = authorizerCode;
        this.authorizerName = authorizerName;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>model_authorizer_rel.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>model_authorizer_rel.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>model_authorizer_rel.model_name</code>. 模型名称
     */
    public String getModelName() {
        return this.modelName;
    }

    /**
     * Setter for <code>model_authorizer_rel.model_name</code>. 模型名称
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * Getter for <code>model_authorizer_rel.authorizer_type</code>.
     * 所有者类型（组织/个人）
     */
    public String getAuthorizerType() {
        return this.authorizerType;
    }

    /**
     * Setter for <code>model_authorizer_rel.authorizer_type</code>.
     * 所有者类型（组织/个人）
     */
    public void setAuthorizerType(String authorizerType) {
        this.authorizerType = authorizerType;
    }

    /**
     * Getter for <code>model_authorizer_rel.authorizer_code</code>. 所有者系统号
     */
    public String getAuthorizerCode() {
        return this.authorizerCode;
    }

    /**
     * Setter for <code>model_authorizer_rel.authorizer_code</code>. 所有者系统号
     */
    public void setAuthorizerCode(String authorizerCode) {
        this.authorizerCode = authorizerCode;
    }

    /**
     * Getter for <code>model_authorizer_rel.authorizer_name</code>. 所有者名称
     */
    public String getAuthorizerName() {
        return this.authorizerName;
    }

    /**
     * Setter for <code>model_authorizer_rel.authorizer_name</code>. 所有者名称
     */
    public void setAuthorizerName(String authorizerName) {
        this.authorizerName = authorizerName;
    }

    /**
     * Getter for <code>model_authorizer_rel.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>model_authorizer_rel.cuid</code>. 创建人id
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>model_authorizer_rel.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>model_authorizer_rel.cu_name</code>. 创建人姓名
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>model_authorizer_rel.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>model_authorizer_rel.muid</code>. 编辑人id
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>model_authorizer_rel.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>model_authorizer_rel.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>model_authorizer_rel.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>model_authorizer_rel.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>model_authorizer_rel.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>model_authorizer_rel.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ModelAuthorizerRelDB other = (ModelAuthorizerRelDB) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.modelName == null) {
            if (other.modelName != null)
                return false;
        }
        else if (!this.modelName.equals(other.modelName))
            return false;
        if (this.authorizerType == null) {
            if (other.authorizerType != null)
                return false;
        }
        else if (!this.authorizerType.equals(other.authorizerType))
            return false;
        if (this.authorizerCode == null) {
            if (other.authorizerCode != null)
                return false;
        }
        else if (!this.authorizerCode.equals(other.authorizerCode))
            return false;
        if (this.authorizerName == null) {
            if (other.authorizerName != null)
                return false;
        }
        else if (!this.authorizerName.equals(other.authorizerName))
            return false;
        if (this.cuid == null) {
            if (other.cuid != null)
                return false;
        }
        else if (!this.cuid.equals(other.cuid))
            return false;
        if (this.cuName == null) {
            if (other.cuName != null)
                return false;
        }
        else if (!this.cuName.equals(other.cuName))
            return false;
        if (this.muid == null) {
            if (other.muid != null)
                return false;
        }
        else if (!this.muid.equals(other.muid))
            return false;
        if (this.muName == null) {
            if (other.muName != null)
                return false;
        }
        else if (!this.muName.equals(other.muName))
            return false;
        if (this.ctime == null) {
            if (other.ctime != null)
                return false;
        }
        else if (!this.ctime.equals(other.ctime))
            return false;
        if (this.mtime == null) {
            if (other.mtime != null)
                return false;
        }
        else if (!this.mtime.equals(other.mtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.modelName == null) ? 0 : this.modelName.hashCode());
        result = prime * result + ((this.authorizerType == null) ? 0 : this.authorizerType.hashCode());
        result = prime * result + ((this.authorizerCode == null) ? 0 : this.authorizerCode.hashCode());
        result = prime * result + ((this.authorizerName == null) ? 0 : this.authorizerName.hashCode());
        result = prime * result + ((this.cuid == null) ? 0 : this.cuid.hashCode());
        result = prime * result + ((this.cuName == null) ? 0 : this.cuName.hashCode());
        result = prime * result + ((this.muid == null) ? 0 : this.muid.hashCode());
        result = prime * result + ((this.muName == null) ? 0 : this.muName.hashCode());
        result = prime * result + ((this.ctime == null) ? 0 : this.ctime.hashCode());
        result = prime * result + ((this.mtime == null) ? 0 : this.mtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ModelAuthorizerRelDB (");

        sb.append(id);
        sb.append(", ").append(modelName);
        sb.append(", ").append(authorizerType);
        sb.append(", ").append(authorizerCode);
        sb.append(", ").append(authorizerName);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
