/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 空间成员信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceMemberDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String spaceCode;
    private String roleCode;
    private String memberName;
    private String memberUid;
    private Byte status;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private Long cuid;
    private Long muid;

    public SpaceMemberDB() {}

    public SpaceMemberDB(SpaceMemberDB value) {
        this.id = value.id;
        this.spaceCode = value.spaceCode;
        this.roleCode = value.roleCode;
        this.memberName = value.memberName;
        this.memberUid = value.memberUid;
        this.status = value.status;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.cuid = value.cuid;
        this.muid = value.muid;
    }

    public SpaceMemberDB(
        Long id,
        String spaceCode,
        String roleCode,
        String memberName,
        String memberUid,
        Byte status,
        LocalDateTime ctime,
        LocalDateTime mtime,
        Long cuid,
        Long muid
    ) {
        this.id = id;
        this.spaceCode = spaceCode;
        this.roleCode = roleCode;
        this.memberName = memberName;
        this.memberUid = memberUid;
        this.status = status;
        this.ctime = ctime;
        this.mtime = mtime;
        this.cuid = cuid;
        this.muid = muid;
    }

    /**
     * Getter for <code>space_member.id</code>. 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>space_member.id</code>. 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>space_member.space_code</code>. 空间编码
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>space_member.space_code</code>. 空间编码
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>space_member.role_code</code>. 角色编码
     */
    public String getRoleCode() {
        return this.roleCode;
    }

    /**
     * Setter for <code>space_member.role_code</code>. 角色编码
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * Getter for <code>space_member.member_name</code>. 成员姓名
     */
    public String getMemberName() {
        return this.memberName;
    }

    /**
     * Setter for <code>space_member.member_name</code>. 成员姓名
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /**
     * Getter for <code>space_member.member_uid</code>. 成员系统号
     */
    public String getMemberUid() {
        return this.memberUid;
    }

    /**
     * Setter for <code>space_member.member_uid</code>. 成员系统号
     */
    public void setMemberUid(String memberUid) {
        this.memberUid = memberUid;
    }

    /**
     * Getter for <code>space_member.status</code>. 删除状态(0未删除，-1已删除)
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>space_member.status</code>. 删除状态(0未删除，-1已删除)
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * Getter for <code>space_member.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>space_member.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>space_member.mtime</code>. 最后一次修改时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>space_member.mtime</code>. 最后一次修改时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>space_member.cuid</code>. 创建人系统号
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>space_member.cuid</code>. 创建人系统号
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>space_member.muid</code>. 最后一次更新人系统号
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>space_member.muid</code>. 最后一次更新人系统号
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SpaceMemberDB other = (SpaceMemberDB) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.spaceCode == null) {
            if (other.spaceCode != null)
                return false;
        }
        else if (!this.spaceCode.equals(other.spaceCode))
            return false;
        if (this.roleCode == null) {
            if (other.roleCode != null)
                return false;
        }
        else if (!this.roleCode.equals(other.roleCode))
            return false;
        if (this.memberName == null) {
            if (other.memberName != null)
                return false;
        }
        else if (!this.memberName.equals(other.memberName))
            return false;
        if (this.memberUid == null) {
            if (other.memberUid != null)
                return false;
        }
        else if (!this.memberUid.equals(other.memberUid))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.ctime == null) {
            if (other.ctime != null)
                return false;
        }
        else if (!this.ctime.equals(other.ctime))
            return false;
        if (this.mtime == null) {
            if (other.mtime != null)
                return false;
        }
        else if (!this.mtime.equals(other.mtime))
            return false;
        if (this.cuid == null) {
            if (other.cuid != null)
                return false;
        }
        else if (!this.cuid.equals(other.cuid))
            return false;
        if (this.muid == null) {
            if (other.muid != null)
                return false;
        }
        else if (!this.muid.equals(other.muid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.spaceCode == null) ? 0 : this.spaceCode.hashCode());
        result = prime * result + ((this.roleCode == null) ? 0 : this.roleCode.hashCode());
        result = prime * result + ((this.memberName == null) ? 0 : this.memberName.hashCode());
        result = prime * result + ((this.memberUid == null) ? 0 : this.memberUid.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.ctime == null) ? 0 : this.ctime.hashCode());
        result = prime * result + ((this.mtime == null) ? 0 : this.mtime.hashCode());
        result = prime * result + ((this.cuid == null) ? 0 : this.cuid.hashCode());
        result = prime * result + ((this.muid == null) ? 0 : this.muid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpaceMemberDB (");

        sb.append(id);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(roleCode);
        sb.append(", ").append(memberName);
        sb.append(", ").append(memberUid);
        sb.append(", ").append(status);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);

        sb.append(")");
        return sb.toString();
    }
}
