/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.Apikey;
import com.ke.bella.openapi.jooqgen.tables.pojos.ApikeyDB;
import com.ke.bella.openapi.jooqgen.tables.records.ApikeyRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * ak
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyDao extends DAOImpl<ApikeyRecord, ApikeyDB, Long> {

    /**
     * Create a new ApikeyDao without any configuration
     */
    public ApikeyDao() {
        super(Apikey.APIKEY, ApikeyDB.class);
    }

    /**
     * Create a new ApikeyDao with an attached configuration
     */
    public ApikeyDao(Configuration configuration) {
        super(Apikey.APIKEY, ApikeyDB.class, configuration);
    }

    @Override
    public Long getId(ApikeyDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Apikey.APIKEY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ApikeyDB> fetchById(Long... values) {
        return fetch(Apikey.APIKEY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ApikeyDB fetchOneById(Long value) {
        return fetchOne(Apikey.APIKEY.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ApikeyDB> fetchOptionalById(Long value) {
        return fetchOptional(Apikey.APIKEY.ID, value);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<ApikeyDB> fetchByCode(String... values) {
        return fetch(Apikey.APIKEY.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public ApikeyDB fetchOneByCode(String value) {
        return fetchOne(Apikey.APIKEY.CODE, value);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public Optional<ApikeyDB> fetchOptionalByCode(String value) {
        return fetchOptional(Apikey.APIKEY.CODE, value);
    }

    /**
     * Fetch records that have <code>ak_sha BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfAkSha(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.AK_SHA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ak_sha IN (values)</code>
     */
    public List<ApikeyDB> fetchByAkSha(String... values) {
        return fetch(Apikey.APIKEY.AK_SHA, values);
    }

    /**
     * Fetch a unique record that has <code>ak_sha = value</code>
     */
    public ApikeyDB fetchOneByAkSha(String value) {
        return fetchOne(Apikey.APIKEY.AK_SHA, value);
    }

    /**
     * Fetch a unique record that has <code>ak_sha = value</code>
     */
    public Optional<ApikeyDB> fetchOptionalByAkSha(String value) {
        return fetchOptional(Apikey.APIKEY.AK_SHA, value);
    }

    /**
     * Fetch records that have <code>ak_display BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfAkDisplay(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.AK_DISPLAY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ak_display IN (values)</code>
     */
    public List<ApikeyDB> fetchByAkDisplay(String... values) {
        return fetch(Apikey.APIKEY.AK_DISPLAY, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ApikeyDB> fetchByName(String... values) {
        return fetch(Apikey.APIKEY.NAME, values);
    }

    /**
     * Fetch records that have <code>parent_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfParentCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.PARENT_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parent_code IN (values)</code>
     */
    public List<ApikeyDB> fetchByParentCode(String... values) {
        return fetch(Apikey.APIKEY.PARENT_CODE, values);
    }

    /**
     * Fetch records that have <code>out_entity_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfOutEntityCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.OUT_ENTITY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>out_entity_code IN (values)</code>
     */
    public List<ApikeyDB> fetchByOutEntityCode(String... values) {
        return fetch(Apikey.APIKEY.OUT_ENTITY_CODE, values);
    }

    /**
     * Fetch records that have <code>service_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfServiceId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.SERVICE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>service_id IN (values)</code>
     */
    public List<ApikeyDB> fetchByServiceId(String... values) {
        return fetch(Apikey.APIKEY.SERVICE_ID, values);
    }

    /**
     * Fetch records that have <code>owner_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfOwnerType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.OWNER_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_type IN (values)</code>
     */
    public List<ApikeyDB> fetchByOwnerType(String... values) {
        return fetch(Apikey.APIKEY.OWNER_TYPE, values);
    }

    /**
     * Fetch records that have <code>owner_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfOwnerCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.OWNER_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_code IN (values)</code>
     */
    public List<ApikeyDB> fetchByOwnerCode(String... values) {
        return fetch(Apikey.APIKEY.OWNER_CODE, values);
    }

    /**
     * Fetch records that have <code>owner_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfOwnerName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.OWNER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_name IN (values)</code>
     */
    public List<ApikeyDB> fetchByOwnerName(String... values) {
        return fetch(Apikey.APIKEY.OWNER_NAME, values);
    }

    /**
     * Fetch records that have <code>manager_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfManagerCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.MANAGER_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>manager_code IN (values)</code>
     */
    public List<ApikeyDB> fetchByManagerCode(String... values) {
        return fetch(Apikey.APIKEY.MANAGER_CODE, values);
    }

    /**
     * Fetch records that have <code>manager_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfManagerName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.MANAGER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>manager_name IN (values)</code>
     */
    public List<ApikeyDB> fetchByManagerName(String... values) {
        return fetch(Apikey.APIKEY.MANAGER_NAME, values);
    }

    /**
     * Fetch records that have <code>role_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfRoleCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.ROLE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_code IN (values)</code>
     */
    public List<ApikeyDB> fetchByRoleCode(String... values) {
        return fetch(Apikey.APIKEY.ROLE_CODE, values);
    }

    /**
     * Fetch records that have <code>certify_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfCertifyCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.CERTIFY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>certify_code IN (values)</code>
     */
    public List<ApikeyDB> fetchByCertifyCode(String... values) {
        return fetch(Apikey.APIKEY.CERTIFY_CODE, values);
    }

    /**
     * Fetch records that have <code>safety_scene_code BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfSafetySceneCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.SAFETY_SCENE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>safety_scene_code IN (values)</code>
     */
    public List<ApikeyDB> fetchBySafetySceneCode(String... values) {
        return fetch(Apikey.APIKEY.SAFETY_SCENE_CODE, values);
    }

    /**
     * Fetch records that have <code>safety_level BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfSafetyLevel(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Apikey.APIKEY.SAFETY_LEVEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>safety_level IN (values)</code>
     */
    public List<ApikeyDB> fetchBySafetyLevel(Byte... values) {
        return fetch(Apikey.APIKEY.SAFETY_LEVEL, values);
    }

    /**
     * Fetch records that have <code>month_quota BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfMonthQuota(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Apikey.APIKEY.MONTH_QUOTA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>month_quota IN (values)</code>
     */
    public List<ApikeyDB> fetchByMonthQuota(BigDecimal... values) {
        return fetch(Apikey.APIKEY.MONTH_QUOTA, values);
    }

    /**
     * Fetch records that have <code>qps_limit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfQpsLimit(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Apikey.APIKEY.QPS_LIMIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>qps_limit IN (values)</code>
     */
    public List<ApikeyDB> fetchByQpsLimit(Integer... values) {
        return fetch(Apikey.APIKEY.QPS_LIMIT, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<ApikeyDB> fetchByStatus(String... values) {
        return fetch(Apikey.APIKEY.STATUS, values);
    }

    /**
     * Fetch records that have <code>remark BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfRemark(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.REMARK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<ApikeyDB> fetchByRemark(String... values) {
        return fetch(Apikey.APIKEY.REMARK, values);
    }

    /**
     * Fetch records that have <code>cuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfCuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Apikey.APIKEY.CUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cuid IN (values)</code>
     */
    public List<ApikeyDB> fetchByCuid(Long... values) {
        return fetch(Apikey.APIKEY.CUID, values);
    }

    /**
     * Fetch records that have <code>cu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfCuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.CU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cu_name IN (values)</code>
     */
    public List<ApikeyDB> fetchByCuName(String... values) {
        return fetch(Apikey.APIKEY.CU_NAME, values);
    }

    /**
     * Fetch records that have <code>muid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfMuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Apikey.APIKEY.MUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>muid IN (values)</code>
     */
    public List<ApikeyDB> fetchByMuid(Long... values) {
        return fetch(Apikey.APIKEY.MUID, values);
    }

    /**
     * Fetch records that have <code>mu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfMuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Apikey.APIKEY.MU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mu_name IN (values)</code>
     */
    public List<ApikeyDB> fetchByMuName(String... values) {
        return fetch(Apikey.APIKEY.MU_NAME, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Apikey.APIKEY.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<ApikeyDB> fetchByCtime(LocalDateTime... values) {
        return fetch(Apikey.APIKEY.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Apikey.APIKEY.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<ApikeyDB> fetchByMtime(LocalDateTime... values) {
        return fetch(Apikey.APIKEY.MTIME, values);
    }
}
