/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.ApikeyMonthCost;
import com.ke.bella.openapi.jooqgen.tables.pojos.ApikeyMonthCostDB;
import com.ke.bella.openapi.jooqgen.tables.records.ApikeyMonthCostRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * ak月花费
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyMonthCostDao extends DAOImpl<ApikeyMonthCostRecord, ApikeyMonthCostDB, Long> {

    /**
     * Create a new ApikeyMonthCostDao without any configuration
     */
    public ApikeyMonthCostDao() {
        super(ApikeyMonthCost.APIKEY_MONTH_COST, ApikeyMonthCostDB.class);
    }

    /**
     * Create a new ApikeyMonthCostDao with an attached configuration
     */
    public ApikeyMonthCostDao(Configuration configuration) {
        super(ApikeyMonthCost.APIKEY_MONTH_COST, ApikeyMonthCostDB.class, configuration);
    }

    @Override
    public Long getId(ApikeyMonthCostDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyMonthCostDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ApikeyMonthCost.APIKEY_MONTH_COST.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ApikeyMonthCostDB> fetchById(Long... values) {
        return fetch(ApikeyMonthCost.APIKEY_MONTH_COST.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ApikeyMonthCostDB fetchOneById(Long value) {
        return fetchOne(ApikeyMonthCost.APIKEY_MONTH_COST.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ApikeyMonthCostDB> fetchOptionalById(Long value) {
        return fetchOptional(ApikeyMonthCost.APIKEY_MONTH_COST.ID, value);
    }

    /**
     * Fetch records that have <code>ak_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyMonthCostDB> fetchRangeOfAkCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(ApikeyMonthCost.APIKEY_MONTH_COST.AK_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ak_code IN (values)</code>
     */
    public List<ApikeyMonthCostDB> fetchByAkCode(String... values) {
        return fetch(ApikeyMonthCost.APIKEY_MONTH_COST.AK_CODE, values);
    }

    /**
     * Fetch records that have <code>month BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyMonthCostDB> fetchRangeOfMonth(String lowerInclusive, String upperInclusive) {
        return fetchRange(ApikeyMonthCost.APIKEY_MONTH_COST.MONTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>month IN (values)</code>
     */
    public List<ApikeyMonthCostDB> fetchByMonth(String... values) {
        return fetch(ApikeyMonthCost.APIKEY_MONTH_COST.MONTH, values);
    }

    /**
     * Fetch records that have <code>amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyMonthCostDB> fetchRangeOfAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ApikeyMonthCost.APIKEY_MONTH_COST.AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<ApikeyMonthCostDB> fetchByAmount(BigDecimal... values) {
        return fetch(ApikeyMonthCost.APIKEY_MONTH_COST.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyMonthCostDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ApikeyMonthCost.APIKEY_MONTH_COST.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<ApikeyMonthCostDB> fetchByCtime(LocalDateTime... values) {
        return fetch(ApikeyMonthCost.APIKEY_MONTH_COST.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ApikeyMonthCostDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ApikeyMonthCost.APIKEY_MONTH_COST.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<ApikeyMonthCostDB> fetchByMtime(LocalDateTime... values) {
        return fetch(ApikeyMonthCost.APIKEY_MONTH_COST.MTIME, values);
    }
}
