/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.EndpointCategoryRel;
import com.ke.bella.openapi.jooqgen.tables.pojos.EndpointCategoryRelDB;
import com.ke.bella.openapi.jooqgen.tables.records.EndpointCategoryRelRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 能力点类目
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EndpointCategoryRelDao extends DAOImpl<EndpointCategoryRelRecord, EndpointCategoryRelDB, Long> {

    /**
     * Create a new EndpointCategoryRelDao without any configuration
     */
    public EndpointCategoryRelDao() {
        super(EndpointCategoryRel.ENDPOINT_CATEGORY_REL, EndpointCategoryRelDB.class);
    }

    /**
     * Create a new EndpointCategoryRelDao with an attached configuration
     */
    public EndpointCategoryRelDao(Configuration configuration) {
        super(EndpointCategoryRel.ENDPOINT_CATEGORY_REL, EndpointCategoryRelDB.class, configuration);
    }

    @Override
    public Long getId(EndpointCategoryRelDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchById(Long... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public EndpointCategoryRelDB fetchOneById(Long value) {
        return fetchOne(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<EndpointCategoryRelDB> fetchOptionalById(Long value) {
        return fetchOptional(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ID, value);
    }

    /**
     * Fetch records that have <code>endpoint BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfEndpoint(String lowerInclusive, String upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ENDPOINT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>endpoint IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByEndpoint(String... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ENDPOINT, values);
    }

    /**
     * Fetch records that have <code>category_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfCategoryCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CATEGORY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category_code IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByCategoryCode(String... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CATEGORY_CODE, values);
    }

    /**
     * Fetch records that have <code>sort BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfSort(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.SORT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchBySort(Integer... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.SORT, values);
    }

    /**
     * Fetch records that have <code>cuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfCuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cuid IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByCuid(Long... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CUID, values);
    }

    /**
     * Fetch records that have <code>cu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfCuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cu_name IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByCuName(String... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CU_NAME, values);
    }

    /**
     * Fetch records that have <code>muid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfMuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>muid IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByMuid(Long... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MUID, values);
    }

    /**
     * Fetch records that have <code>mu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfMuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mu_name IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByMuName(String... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MU_NAME, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByCtime(LocalDateTime... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<EndpointCategoryRelDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<EndpointCategoryRelDB> fetchByMtime(LocalDateTime... values) {
        return fetch(EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MTIME, values);
    }
}
