/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.Instance;
import com.ke.bella.openapi.jooqgen.tables.pojos.InstanceDB;
import com.ke.bella.openapi.jooqgen.tables.records.InstanceRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstanceDao extends DAOImpl<InstanceRecord, InstanceDB, Long> {

    /**
     * Create a new InstanceDao without any configuration
     */
    public InstanceDao() {
        super(Instance.INSTANCE, InstanceDB.class);
    }

    /**
     * Create a new InstanceDao with an attached configuration
     */
    public InstanceDao(Configuration configuration) {
        super(Instance.INSTANCE, InstanceDB.class, configuration);
    }

    @Override
    public Long getId(InstanceDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<InstanceDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Instance.INSTANCE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<InstanceDB> fetchById(Long... values) {
        return fetch(Instance.INSTANCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public InstanceDB fetchOneById(Long value) {
        return fetchOne(Instance.INSTANCE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<InstanceDB> fetchOptionalById(Long value) {
        return fetchOptional(Instance.INSTANCE.ID, value);
    }

    /**
     * Fetch records that have <code>ip BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<InstanceDB> fetchRangeOfIp(String lowerInclusive, String upperInclusive) {
        return fetchRange(Instance.INSTANCE.IP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<InstanceDB> fetchByIp(String... values) {
        return fetch(Instance.INSTANCE.IP, values);
    }

    /**
     * Fetch records that have <code>port BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<InstanceDB> fetchRangeOfPort(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Instance.INSTANCE.PORT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>port IN (values)</code>
     */
    public List<InstanceDB> fetchByPort(Integer... values) {
        return fetch(Instance.INSTANCE.PORT, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<InstanceDB> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Instance.INSTANCE.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<InstanceDB> fetchByStatus(Integer... values) {
        return fetch(Instance.INSTANCE.STATUS, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<InstanceDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Instance.INSTANCE.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<InstanceDB> fetchByCtime(LocalDateTime... values) {
        return fetch(Instance.INSTANCE.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<InstanceDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Instance.INSTANCE.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<InstanceDB> fetchByMtime(LocalDateTime... values) {
        return fetch(Instance.INSTANCE.MTIME, values);
    }
}
