/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.ModelAuthorizerRel;
import com.ke.bella.openapi.jooqgen.tables.pojos.ModelAuthorizerRelDB;
import com.ke.bella.openapi.jooqgen.tables.records.ModelAuthorizerRelRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 模型授权信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelAuthorizerRelDao extends DAOImpl<ModelAuthorizerRelRecord, ModelAuthorizerRelDB, Long> {

    /**
     * Create a new ModelAuthorizerRelDao without any configuration
     */
    public ModelAuthorizerRelDao() {
        super(ModelAuthorizerRel.MODEL_AUTHORIZER_REL, ModelAuthorizerRelDB.class);
    }

    /**
     * Create a new ModelAuthorizerRelDao with an attached configuration
     */
    public ModelAuthorizerRelDao(Configuration configuration) {
        super(ModelAuthorizerRel.MODEL_AUTHORIZER_REL, ModelAuthorizerRelDB.class, configuration);
    }

    @Override
    public Long getId(ModelAuthorizerRelDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchById(Long... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ModelAuthorizerRelDB fetchOneById(Long value) {
        return fetchOne(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ModelAuthorizerRelDB> fetchOptionalById(Long value) {
        return fetchOptional(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.ID, value);
    }

    /**
     * Fetch records that have <code>model_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfModelName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MODEL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>model_name IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByModelName(String... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MODEL_NAME, values);
    }

    /**
     * Fetch records that have <code>authorizer_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfAuthorizerType(String lowerInclusive, String upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorizer_type IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByAuthorizerType(String... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_TYPE, values);
    }

    /**
     * Fetch records that have <code>authorizer_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfAuthorizerCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorizer_code IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByAuthorizerCode(String... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_CODE, values);
    }

    /**
     * Fetch records that have <code>authorizer_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfAuthorizerName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorizer_name IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByAuthorizerName(String... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_NAME, values);
    }

    /**
     * Fetch records that have <code>cuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfCuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.CUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cuid IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByCuid(Long... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.CUID, values);
    }

    /**
     * Fetch records that have <code>cu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfCuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.CU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cu_name IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByCuName(String... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.CU_NAME, values);
    }

    /**
     * Fetch records that have <code>muid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfMuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>muid IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByMuid(Long... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MUID, values);
    }

    /**
     * Fetch records that have <code>mu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfMuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mu_name IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByMuName(String... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MU_NAME, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByCtime(LocalDateTime... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelAuthorizerRelDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<ModelAuthorizerRelDB> fetchByMtime(LocalDateTime... values) {
        return fetch(ModelAuthorizerRel.MODEL_AUTHORIZER_REL.MTIME, values);
    }
}
