/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.Model;
import com.ke.bella.openapi.jooqgen.tables.pojos.ModelDB;
import com.ke.bella.openapi.jooqgen.tables.records.ModelRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 模型
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelDao extends DAOImpl<ModelRecord, ModelDB, Long> {

    /**
     * Create a new ModelDao without any configuration
     */
    public ModelDao() {
        super(Model.MODEL, ModelDB.class);
    }

    /**
     * Create a new ModelDao with an attached configuration
     */
    public ModelDao(Configuration configuration) {
        super(Model.MODEL, ModelDB.class, configuration);
    }

    @Override
    public Long getId(ModelDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Model.MODEL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ModelDB> fetchById(Long... values) {
        return fetch(Model.MODEL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ModelDB fetchOneById(Long value) {
        return fetchOne(Model.MODEL.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ModelDB> fetchOptionalById(Long value) {
        return fetchOptional(Model.MODEL.ID, value);
    }

    /**
     * Fetch records that have <code>model_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfModelName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.MODEL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>model_name IN (values)</code>
     */
    public List<ModelDB> fetchByModelName(String... values) {
        return fetch(Model.MODEL.MODEL_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>model_name = value</code>
     */
    public ModelDB fetchOneByModelName(String value) {
        return fetchOne(Model.MODEL.MODEL_NAME, value);
    }

    /**
     * Fetch a unique record that has <code>model_name = value</code>
     */
    public Optional<ModelDB> fetchOptionalByModelName(String value) {
        return fetchOptional(Model.MODEL.MODEL_NAME, value);
    }

    /**
     * Fetch records that have <code>document_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfDocumentUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.DOCUMENT_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>document_url IN (values)</code>
     */
    public List<ModelDB> fetchByDocumentUrl(String... values) {
        return fetch(Model.MODEL.DOCUMENT_URL, values);
    }

    /**
     * Fetch records that have <code>visibility BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfVisibility(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.VISIBILITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>visibility IN (values)</code>
     */
    public List<ModelDB> fetchByVisibility(String... values) {
        return fetch(Model.MODEL.VISIBILITY, values);
    }

    /**
     * Fetch records that have <code>openness_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfOpennessType(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Model.MODEL.OPENNESS_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>openness_type IN (values)</code>
     */
    public List<ModelDB> fetchByOpennessType(Byte... values) {
        return fetch(Model.MODEL.OPENNESS_TYPE, values);
    }

    /**
     * Fetch records that have <code>owner_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfOwnerType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.OWNER_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_type IN (values)</code>
     */
    public List<ModelDB> fetchByOwnerType(String... values) {
        return fetch(Model.MODEL.OWNER_TYPE, values);
    }

    /**
     * Fetch records that have <code>owner_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfOwnerCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.OWNER_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_code IN (values)</code>
     */
    public List<ModelDB> fetchByOwnerCode(String... values) {
        return fetch(Model.MODEL.OWNER_CODE, values);
    }

    /**
     * Fetch records that have <code>owner_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfOwnerName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.OWNER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_name IN (values)</code>
     */
    public List<ModelDB> fetchByOwnerName(String... values) {
        return fetch(Model.MODEL.OWNER_NAME, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<ModelDB> fetchByStatus(String... values) {
        return fetch(Model.MODEL.STATUS, values);
    }

    /**
     * Fetch records that have <code>properties BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfProperties(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.PROPERTIES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>properties IN (values)</code>
     */
    public List<ModelDB> fetchByProperties(String... values) {
        return fetch(Model.MODEL.PROPERTIES, values);
    }

    /**
     * Fetch records that have <code>features BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfFeatures(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.FEATURES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>features IN (values)</code>
     */
    public List<ModelDB> fetchByFeatures(String... values) {
        return fetch(Model.MODEL.FEATURES, values);
    }

    /**
     * Fetch records that have <code>linked_to BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfLinkedTo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.LINKED_TO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>linked_to IN (values)</code>
     */
    public List<ModelDB> fetchByLinkedTo(String... values) {
        return fetch(Model.MODEL.LINKED_TO, values);
    }

    /**
     * Fetch records that have <code>cuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfCuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Model.MODEL.CUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cuid IN (values)</code>
     */
    public List<ModelDB> fetchByCuid(Long... values) {
        return fetch(Model.MODEL.CUID, values);
    }

    /**
     * Fetch records that have <code>cu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfCuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.CU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cu_name IN (values)</code>
     */
    public List<ModelDB> fetchByCuName(String... values) {
        return fetch(Model.MODEL.CU_NAME, values);
    }

    /**
     * Fetch records that have <code>muid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfMuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Model.MODEL.MUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>muid IN (values)</code>
     */
    public List<ModelDB> fetchByMuid(Long... values) {
        return fetch(Model.MODEL.MUID, values);
    }

    /**
     * Fetch records that have <code>mu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfMuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Model.MODEL.MU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mu_name IN (values)</code>
     */
    public List<ModelDB> fetchByMuName(String... values) {
        return fetch(Model.MODEL.MU_NAME, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Model.MODEL.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<ModelDB> fetchByCtime(LocalDateTime... values) {
        return fetch(Model.MODEL.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ModelDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Model.MODEL.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<ModelDB> fetchByMtime(LocalDateTime... values) {
        return fetch(Model.MODEL.MTIME, values);
    }
}
