/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.SpaceMember;
import com.ke.bella.openapi.jooqgen.tables.pojos.SpaceMemberDB;
import com.ke.bella.openapi.jooqgen.tables.records.SpaceMemberRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 空间成员信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceMemberDao extends DAOImpl<SpaceMemberRecord, SpaceMemberDB, Long> {

    /**
     * Create a new SpaceMemberDao without any configuration
     */
    public SpaceMemberDao() {
        super(SpaceMember.SPACE_MEMBER, SpaceMemberDB.class);
    }

    /**
     * Create a new SpaceMemberDao with an attached configuration
     */
    public SpaceMemberDao(Configuration configuration) {
        super(SpaceMember.SPACE_MEMBER, SpaceMemberDB.class, configuration);
    }

    @Override
    public Long getId(SpaceMemberDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SpaceMemberDB> fetchById(Long... values) {
        return fetch(SpaceMember.SPACE_MEMBER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SpaceMemberDB fetchOneById(Long value) {
        return fetchOne(SpaceMember.SPACE_MEMBER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<SpaceMemberDB> fetchOptionalById(Long value) {
        return fetchOptional(SpaceMember.SPACE_MEMBER.ID, value);
    }

    /**
     * Fetch records that have <code>space_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfSpaceCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.SPACE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>space_code IN (values)</code>
     */
    public List<SpaceMemberDB> fetchBySpaceCode(String... values) {
        return fetch(SpaceMember.SPACE_MEMBER.SPACE_CODE, values);
    }

    /**
     * Fetch records that have <code>role_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfRoleCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.ROLE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_code IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByRoleCode(String... values) {
        return fetch(SpaceMember.SPACE_MEMBER.ROLE_CODE, values);
    }

    /**
     * Fetch records that have <code>member_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfMemberName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.MEMBER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>member_name IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByMemberName(String... values) {
        return fetch(SpaceMember.SPACE_MEMBER.MEMBER_NAME, values);
    }

    /**
     * Fetch records that have <code>member_uid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfMemberUid(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.MEMBER_UID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>member_uid IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByMemberUid(String... values) {
        return fetch(SpaceMember.SPACE_MEMBER.MEMBER_UID, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByStatus(Byte... values) {
        return fetch(SpaceMember.SPACE_MEMBER.STATUS, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByCtime(LocalDateTime... values) {
        return fetch(SpaceMember.SPACE_MEMBER.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByMtime(LocalDateTime... values) {
        return fetch(SpaceMember.SPACE_MEMBER.MTIME, values);
    }

    /**
     * Fetch records that have <code>cuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfCuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.CUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cuid IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByCuid(Long... values) {
        return fetch(SpaceMember.SPACE_MEMBER.CUID, values);
    }

    /**
     * Fetch records that have <code>muid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceMemberDB> fetchRangeOfMuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpaceMember.SPACE_MEMBER.MUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>muid IN (values)</code>
     */
    public List<SpaceMemberDB> fetchByMuid(Long... values) {
        return fetch(SpaceMember.SPACE_MEMBER.MUID, values);
    }
}
