/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.SpaceRole;
import com.ke.bella.openapi.jooqgen.tables.pojos.SpaceRoleDB;
import com.ke.bella.openapi.jooqgen.tables.records.SpaceRoleRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 空间角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceRoleDao extends DAOImpl<SpaceRoleRecord, SpaceRoleDB, Long> {

    /**
     * Create a new SpaceRoleDao without any configuration
     */
    public SpaceRoleDao() {
        super(SpaceRole.SPACE_ROLE, SpaceRoleDB.class);
    }

    /**
     * Create a new SpaceRoleDao with an attached configuration
     */
    public SpaceRoleDao(Configuration configuration) {
        super(SpaceRole.SPACE_ROLE, SpaceRoleDB.class, configuration);
    }

    @Override
    public Long getId(SpaceRoleDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SpaceRoleDB> fetchById(Long... values) {
        return fetch(SpaceRole.SPACE_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SpaceRoleDB fetchOneById(Long value) {
        return fetchOne(SpaceRole.SPACE_ROLE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<SpaceRoleDB> fetchOptionalById(Long value) {
        return fetchOptional(SpaceRole.SPACE_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>space_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfSpaceCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.SPACE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>space_code IN (values)</code>
     */
    public List<SpaceRoleDB> fetchBySpaceCode(String... values) {
        return fetch(SpaceRole.SPACE_ROLE.SPACE_CODE, values);
    }

    /**
     * Fetch records that have <code>role_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfRoleCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.ROLE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_code IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByRoleCode(String... values) {
        return fetch(SpaceRole.SPACE_ROLE.ROLE_CODE, values);
    }

    /**
     * Fetch records that have <code>role_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfRoleName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.ROLE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_name IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByRoleName(String... values) {
        return fetch(SpaceRole.SPACE_ROLE.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>role_desc BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfRoleDesc(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.ROLE_DESC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_desc IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByRoleDesc(String... values) {
        return fetch(SpaceRole.SPACE_ROLE.ROLE_DESC, values);
    }

    /**
     * Fetch records that have <code>role_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfRoleType(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.ROLE_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_type IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByRoleType(Byte... values) {
        return fetch(SpaceRole.SPACE_ROLE.ROLE_TYPE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByStatus(Byte... values) {
        return fetch(SpaceRole.SPACE_ROLE.STATUS, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByCtime(LocalDateTime... values) {
        return fetch(SpaceRole.SPACE_ROLE.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByMtime(LocalDateTime... values) {
        return fetch(SpaceRole.SPACE_ROLE.MTIME, values);
    }

    /**
     * Fetch records that have <code>cuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfCuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.CUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cuid IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByCuid(Long... values) {
        return fetch(SpaceRole.SPACE_ROLE.CUID, values);
    }

    /**
     * Fetch records that have <code>muid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<SpaceRoleDB> fetchRangeOfMuid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpaceRole.SPACE_ROLE.MUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>muid IN (values)</code>
     */
    public List<SpaceRoleDB> fetchByMuid(Long... values) {
        return fetch(SpaceRole.SPACE_ROLE.MUID, values);
    }
}
