/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.daos;


import com.ke.bella.openapi.jooqgen.tables.User;
import com.ke.bella.openapi.jooqgen.tables.pojos.UserDB;
import com.ke.bella.openapi.jooqgen.tables.records.UserRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, UserDB, Long> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, UserDB.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, UserDB.class, configuration);
    }

    @Override
    public Long getId(UserDB object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(User.USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<UserDB> fetchById(Long... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public UserDB fetchOneById(Long value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<UserDB> fetchOptionalById(Long value) {
        return fetchOptional(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>user_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfUserName(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.USER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<UserDB> fetchByUserName(String... values) {
        return fetch(User.USER.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<UserDB> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfPassword(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.PASSWORD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<UserDB> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>source BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfSource(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.SOURCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<UserDB> fetchBySource(String... values) {
        return fetch(User.USER.SOURCE, values);
    }

    /**
     * Fetch records that have <code>source_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfSourceId(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.SOURCE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>source_id IN (values)</code>
     */
    public List<UserDB> fetchBySourceId(String... values) {
        return fetch(User.USER.SOURCE_ID, values);
    }

    /**
     * Fetch records that have <code>manager_ak BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfManagerAk(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.MANAGER_AK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>manager_ak IN (values)</code>
     */
    public List<UserDB> fetchByManagerAk(String... values) {
        return fetch(User.USER.MANAGER_AK, values);
    }

    /**
     * Fetch records that have <code>optional_info BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfOptionalInfo(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.OPTIONAL_INFO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>optional_info IN (values)</code>
     */
    public List<UserDB> fetchByOptionalInfo(String... values) {
        return fetch(User.USER.OPTIONAL_INFO, values);
    }

    /**
     * Fetch records that have <code>ctime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfCtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.CTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<UserDB> fetchByCtime(LocalDateTime... values) {
        return fetch(User.USER.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserDB> fetchRangeOfMtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.MTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<UserDB> fetchByMtime(LocalDateTime... values) {
        return fetch(User.USER.MTIME, values);
    }
}
