/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.jooqgen.tables.records;


import com.ke.bella.openapi.jooqgen.tables.ApikeyTransferLog;
import com.ke.bella.openapi.jooqgen.tables.pojos.ApikeyTransferLogDB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * API Key所有权转移审计日志表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyTransferLogRecord extends UpdatableRecordImpl<ApikeyTransferLogRecord> implements Record14<Long, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apikey_transfer_log.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>apikey_transfer_log.ak_code</code>. API Key编码
     */
    public void setAkCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.ak_code</code>. API Key编码
     */
    public String getAkCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apikey_transfer_log.from_owner_type</code>. 原所有者类型
     */
    public void setFromOwnerType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.from_owner_type</code>. 原所有者类型
     */
    public String getFromOwnerType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apikey_transfer_log.from_owner_code</code>. 原所有者编码
     */
    public void setFromOwnerCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.from_owner_code</code>. 原所有者编码
     */
    public String getFromOwnerCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>apikey_transfer_log.from_owner_name</code>. 原所有者姓名
     */
    public void setFromOwnerName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.from_owner_name</code>. 原所有者姓名
     */
    public String getFromOwnerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>apikey_transfer_log.to_owner_type</code>. 新所有者类型
     */
    public void setToOwnerType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.to_owner_type</code>. 新所有者类型
     */
    public String getToOwnerType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>apikey_transfer_log.to_owner_code</code>. 新所有者编码
     */
    public void setToOwnerCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.to_owner_code</code>. 新所有者编码
     */
    public String getToOwnerCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>apikey_transfer_log.to_owner_name</code>. 新所有者姓名
     */
    public void setToOwnerName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.to_owner_name</code>. 新所有者姓名
     */
    public String getToOwnerName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>apikey_transfer_log.transfer_reason</code>. 转移原因
     */
    public void setTransferReason(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.transfer_reason</code>. 转移原因
     */
    public String getTransferReason() {
        return (String) get(8);
    }

    /**
     * Setter for <code>apikey_transfer_log.status</code>.
     * 转移状态(pending/completed/failed)
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.status</code>.
     * 转移状态(pending/completed/failed)
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>apikey_transfer_log.operator_uid</code>. 操作人用户ID
     */
    public void setOperatorUid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.operator_uid</code>. 操作人用户ID
     */
    public Long getOperatorUid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>apikey_transfer_log.operator_name</code>. 操作人姓名
     */
    public void setOperatorName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.operator_name</code>. 操作人姓名
     */
    public String getOperatorName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>apikey_transfer_log.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>apikey_transfer_log.mtime</code>. 更新时间
     */
    public void setMtime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>apikey_transfer_log.mtime</code>. 更新时间
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.ID;
    }

    @Override
    public Field<String> field2() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.AK_CODE;
    }

    @Override
    public Field<String> field3() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_TYPE;
    }

    @Override
    public Field<String> field4() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_CODE;
    }

    @Override
    public Field<String> field5() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_NAME;
    }

    @Override
    public Field<String> field6() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_TYPE;
    }

    @Override
    public Field<String> field7() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_CODE;
    }

    @Override
    public Field<String> field8() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_NAME;
    }

    @Override
    public Field<String> field9() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.TRANSFER_REASON;
    }

    @Override
    public Field<String> field10() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.STATUS;
    }

    @Override
    public Field<Long> field11() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.OPERATOR_UID;
    }

    @Override
    public Field<String> field12() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.OPERATOR_NAME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.CTIME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return ApikeyTransferLog.APIKEY_TRANSFER_LOG.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAkCode();
    }

    @Override
    public String component3() {
        return getFromOwnerType();
    }

    @Override
    public String component4() {
        return getFromOwnerCode();
    }

    @Override
    public String component5() {
        return getFromOwnerName();
    }

    @Override
    public String component6() {
        return getToOwnerType();
    }

    @Override
    public String component7() {
        return getToOwnerCode();
    }

    @Override
    public String component8() {
        return getToOwnerName();
    }

    @Override
    public String component9() {
        return getTransferReason();
    }

    @Override
    public String component10() {
        return getStatus();
    }

    @Override
    public Long component11() {
        return getOperatorUid();
    }

    @Override
    public String component12() {
        return getOperatorName();
    }

    @Override
    public LocalDateTime component13() {
        return getCtime();
    }

    @Override
    public LocalDateTime component14() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAkCode();
    }

    @Override
    public String value3() {
        return getFromOwnerType();
    }

    @Override
    public String value4() {
        return getFromOwnerCode();
    }

    @Override
    public String value5() {
        return getFromOwnerName();
    }

    @Override
    public String value6() {
        return getToOwnerType();
    }

    @Override
    public String value7() {
        return getToOwnerCode();
    }

    @Override
    public String value8() {
        return getToOwnerName();
    }

    @Override
    public String value9() {
        return getTransferReason();
    }

    @Override
    public String value10() {
        return getStatus();
    }

    @Override
    public Long value11() {
        return getOperatorUid();
    }

    @Override
    public String value12() {
        return getOperatorName();
    }

    @Override
    public LocalDateTime value13() {
        return getCtime();
    }

    @Override
    public LocalDateTime value14() {
        return getMtime();
    }

    @Override
    public ApikeyTransferLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value2(String value) {
        setAkCode(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value3(String value) {
        setFromOwnerType(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value4(String value) {
        setFromOwnerCode(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value5(String value) {
        setFromOwnerName(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value6(String value) {
        setToOwnerType(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value7(String value) {
        setToOwnerCode(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value8(String value) {
        setToOwnerName(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value9(String value) {
        setTransferReason(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value10(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value11(Long value) {
        setOperatorUid(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value12(String value) {
        setOperatorName(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value13(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord value14(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ApikeyTransferLogRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Long value11, String value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApikeyTransferLogRecord
     */
    public ApikeyTransferLogRecord() {
        super(ApikeyTransferLog.APIKEY_TRANSFER_LOG);
    }

    /**
     * Create a detached, initialised ApikeyTransferLogRecord
     */
    public ApikeyTransferLogRecord(Long id, String akCode, String fromOwnerType, String fromOwnerCode, String fromOwnerName, String toOwnerType, String toOwnerCode, String toOwnerName, String transferReason, String status, Long operatorUid, String operatorName, LocalDateTime ctime, LocalDateTime mtime) {
        super(ApikeyTransferLog.APIKEY_TRANSFER_LOG);

        setId(id);
        setAkCode(akCode);
        setFromOwnerType(fromOwnerType);
        setFromOwnerCode(fromOwnerCode);
        setFromOwnerName(fromOwnerName);
        setToOwnerType(toOwnerType);
        setToOwnerCode(toOwnerCode);
        setToOwnerName(toOwnerName);
        setTransferReason(transferReason);
        setStatus(status);
        setOperatorUid(operatorUid);
        setOperatorName(operatorName);
        setCtime(ctime);
        setMtime(mtime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ApikeyTransferLogRecord
     */
    public ApikeyTransferLogRecord(ApikeyTransferLogDB value) {
        super(ApikeyTransferLog.APIKEY_TRANSFER_LOG);

        if (value != null) {
            setId(value.getId());
            setAkCode(value.getAkCode());
            setFromOwnerType(value.getFromOwnerType());
            setFromOwnerCode(value.getFromOwnerCode());
            setFromOwnerName(value.getFromOwnerName());
            setToOwnerType(value.getToOwnerType());
            setToOwnerCode(value.getToOwnerCode());
            setToOwnerName(value.getToOwnerName());
            setTransferReason(value.getTransferReason());
            setStatus(value.getStatus());
            setOperatorUid(value.getOperatorUid());
            setOperatorName(value.getOperatorName());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
            resetChangedOnNotNull();
        }
    }
}
